runtime: nodejs
vm: true
service: gma-village-graphql-STAGE
health_check:
  enable_health_check: False
env_variables:
  AK_APP_SECRET: YOUR_AK_APP_SECRET
  CSRF: UUID
  SQS_AWS_ACCESS_KEY: YOUR_SQS_AWS_ACCESS_KEY
  SQS_AWS_SECRET_KEY: YOUR_SQS_AWS_SECRET_KEY
  SQS_QUEUE_URL: YOUR_SQS_QUEUE_URL
