
// ACCOUNT KIT
export const INIT_ACCOUNT_KIT_REQUEST = "INIT_ACCOUNT_KIT_REQUEST"
export const INIT_ACCOUNT_KIT_REQUEST_SUCCESS = "INIT_ACCOUNT_KIT_REQUEST_SUCCESS"
export const INIT_ACCOUNT_KIT_REQUEST_FAILURE = "INIT_ACCOUNT_KIT_REQUEST_FAILURE"
export const ACCOUNT_KIT_AUTH_REQUEST = "ACCOUNT_KIT_AUTH_REQUEST"
export const ACCOUNT_KIT_AUTH_REQUEST_SUCCESS = "ACCOUNT_KIT_AUTH_REQUEST_SUCCESS"
export const ACCOUNT_KIT_AUTH_REQUEST_FAILURE = "ACCOUNT_KIT_AUTH_REQUEST_FAILURE"

// AUTH
export const CHECK_AUTH_COOKIE = "CHECK_AUTH_COOKIE"
export const CHECK_AUTH_COOKIE_SUCCESS = "CHECK_AUTH_COOKIE_SUCCESS"
export const CHECK_AUTH_COOKIE_FAILURE = "CHECK_AUTH_COOKIE_FAILURE"
export const SAVE_AUTH_COOKIE = "SAVE_AUTH_COOKIE"
export const REMOVE_AUTH_COOKIE = "REMOVE_AUTH_COOKIE"
export const CURRENT_USER_REQUEST = "CURRENT_USER_REQUEST"
export const CURRENT_USER_REQUEST_SUCCESS = "CURRENT_USER_REQUEST_SUCCESS"
export const CURRENT_USER_REQUEST_FAILURE = "CURRENT_USER_REQUEST_FAILURE"
export const LOGOUT_REQUEST = "LOGOUT_REQUEST"


// ADMIN
export const INIT_ADMIN_LIST_REQUEST = "INIT_ADMIN_LIST_REQUEST"
export const INIT_ADMIN_LIST_REQUEST_SUCCESS = "INIT_ADMIN_LIST_REQUEST_SUCCESS"
export const INIT_ADMIN_LIST_REQUEST_FAILURE = "INIT_ADMIN_LIST_REQUEST_FAILURE"
export const FETCH_ADMIN_REQUEST = "FETCH_ADMIN_REQUEST"
export const FETCH_ADMIN_REQUEST_SUCCESS = "FETCH_ADMIN_REQUEST_SUCCESS"
export const FETCH_ADMIN_REQUEST_FAILURE = "FETCH_ADMIN_REQUEST_FAILURE"
export const SAVE_ADMIN_USER_REQUEST = "SAVE_ADMIN_USER_REQUEST"
export const SAVE_ADMIN_USER_REQUEST_SUCCESS = "SAVE_ADMIN_USER_REQUEST_SUCCESS"
export const SAVE_ADMIN_USER_REQUEST_FAILURE = "SAVE_ADMIN_USER_REQUEST_FAILURE"
export const RESET_SAVE_ADMIN_USER_REQUEST = "RESET_SAVE_ADMIN_USER_REQUEST"

// GMA
export const FETCH_GMA_REQUEST = "FETCH_GMA_REQUEST"
export const FETCH_GMA_REQUEST_SUCCESS = "FETCH_GMA_REQUEST_SUCCESS"
export const FETCH_GMA_REQUEST_FAILURE = "FETCH_GMA_REQUEST_FAILURE"
export const SAVE_GMA_USER_REQUEST = "SAVE_GMA_USER_REQUEST"
export const SAVE_GMA_USER_REQUEST_SUCCESS = "SAVE_GMA_USER_REQUEST_SUCCESS"
export const SAVE_GMA_USER_REQUEST_FAILURE = "SAVE_GMA_USER_REQUEST_FAILURE"
export const RESET_SAVE_GMA_USER_REQUEST = "RESET_SAVE_GMA_USER_REQUEST"
export const INIT_GMAS_LIST_REQUEST = "INIT_GMAS_LIST_REQUEST"
export const INIT_GMAS_LIST_REQUEST_SUCCESS = "INIT_GMAS_LIST_REQUEST_SUCCESS"
export const INIT_GMAS_LIST_REQUEST_FAILURE = "INIT_GMAS_LIST_REQUEST_FAILURE"
export const FILTER_GMAS_LIST = "FILTER_GMAS_LIST"

// PARENT
export const INIT_PARENT_LIST_REQUEST = "INIT_PARENT_LIST_REQUEST"
export const INIT_PARENT_LIST_REQUEST_SUCCESS = "INIT_PARENT_LIST_REQUEST_SUCCESS"
export const INIT_PARENT_LIST_REQUEST_FAILURE = "INIT_PARENT_LIST_REQUEST_FAILURE"
export const FETCH_PARENT_REQUEST = "FETCH_PARENT_REQUEST"
export const FETCH_PARENT_REQUEST_SUCCESS = "FETCH_PARENT_REQUEST_SUCCESS"
export const FETCH_PARENT_REQUEST_FAILURE = "FETCH_PARENT_REQUEST_FAILURE"
export const SAVE_PARENT_USER_REQUEST = "SAVE_PARENT_USER_REQUEST"
export const SAVE_PARENT_USER_REQUEST_SUCCESS = "SAVE_PARENT_USER_REQUEST_SUCCESS"
export const SAVE_PARENT_USER_REQUEST_FAILURE = "SAVE_PARENT_USER_REQUEST_FAILURE"
export const RESET_SAVE_PARENT_USER_REQUEST = "RESET_SAVE_PARENT_USER_REQUEST"

// UPLOAD IMAGE
export const SIGNED_URL_REQUEST = "SIGNED_URL_REQUEST"
export const SIGNED_URL_REQUEST_SUCCESS = "SIGNED_URL_REQUEST_SUCCESS"
export const SIGNED_URL_REQUEST_FAILURE = "SIGNED_URL_REQUEST_FAILURE"
export const PRE_UPLOAD_IMAGE_REQUEST = "PRE_UPLOAD_IMAGE_REQUEST"
export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST"
export const UPLOAD_IMAGE_REQUEST_SUCCESS = "UPLOAD_IMAGE_REQUEST_SUCCESS"
export const UPLOAD_IMAGE_REQUEST_FAILURE = "UPLOAD_IMAGE_REQUEST_FAILURE"
export const RESET_UPLOAD_IMAGE_REQUEST = "RESET_UPLOAD_IMAGE_REQUEST"

// CARE NEED
export const SAVE_CARE_NEED_REQUEST = "SAVE_CARE_NEED_REQUEST"
export const SAVE_CARE_NEED_REQUEST_SUCCESS = "SAVE_CARE_NEED_REQUEST_SUCCESS"
export const SAVE_CARE_NEED_REQUEST_FAILURE = "SAVE_CARE_NEED_REQUEST_FAILURE"
export const RESET_SAVE_CARE_NEED_REQUEST = "RESET_SAVE_CARE_NEED_REQUEST"
